version: "3.9"

services:
  grabbler-backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile
    container_name: grabbler-backend
    environment:
      AUDIO_OUTPUT_DIR: /downloads
    #e.g:  /Users/tim/dev/grabbler/t
    volumes:
      - ${DOWNLOAD_FOLDER}:/downloads
    ports:
      - "3333:3333"
    restart: unless-stopped

  grabbler-frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    container_name: grabbler-frontend
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - grabbler-backend
    restart: unless-stopped
  
networks:
  default:
    name: grabbler-net
